import Paragraph from './paragraph';
import Heading2 from './heading2';
import Heading3 from './heading3';
import ListItem from './list-item';
import BulletList from './bullet-list';
import OrderedList from './ordered-list';
import Table from './table';
import Underline from './underline';
import Strike from './strike';
import Strong from './strong';
import Link from './link';
import Trash from './trash';
import MoveUp from './move-up';
import MoveDown from './move-down';
declare const _default: (Paragraph | Heading2 | Heading3 | ListItem | BulletList | OrderedList | Table | Underline | Strike | Strong | Link | Trash | MoveUp | MoveDown)[];
export default _default;
