import Paragraph from './paragraph';
import Heading2 from './heading2';
import Heading3 from './heading3';
import ListItem from './list-item';
import BulletList from './bullet-list';
import OrderedList from './ordered-list';
import BlockQuote from './blockquote';
import Underline from './underline';
import Strike from './strike';
import Strong from './strong';
import Link from './link';
import Bold from './bold';
import Trash from './trash';
import MoveUp from './move-up';
import MoveDown from './move-down';
import DefaultKeys from './default-keys';
import DefaultPlugins from './default-plugins';
declare const _default: (Paragraph | Heading2 | Heading3 | ListItem | BulletList | OrderedList | BlockQuote | Underline | Strike | Strong | Link | Bold | Trash | MoveUp | MoveDown | DefaultKeys | DefaultPlugins)[];
export default _default;
