import Paragraph from './paragraph';
import Heading2 from './heading2';
import Heading3 from './heading3';
import ListItem from './list-item';
import BulletList from './bullet-list';
import OrderedList from './ordered-list';
import Underline from './underline';
import Strike from './strike';
import Strong from './strong';
import Link from './link';
import Lift from './lift';
declare const _default: (Paragraph | Heading2 | Heading3 | ListItem | BulletList | OrderedList | Underline | Strike | Strong | Link | Lift)[];
export default _default;
